CREATE DATABASE IF NOT EXISTS bhms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bhms;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  full_name VARCHAR(120) NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  phone_number VARCHAR(30) NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'Tenant',
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  verification_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  verification_type VARCHAR(30) NOT NULL DEFAULT 'Student ID',
  verification_document_url TEXT NULL,
  verification_token VARCHAR(120) NULL,
  verification_token_expires DATETIME NULL,
  password_reset_token VARCHAR(120) NULL,
  password_reset_expires DATETIME NULL,
  password_reset_otp VARCHAR(255) NULL,
  password_reset_otp_expires DATETIME NULL,
  password_reset_otp_requested_at DATETIME NULL,
  password_reset_otp_request_count INT NOT NULL DEFAULT 0,
  password_reset_otp_window_started_at DATETIME NULL,
  profile_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role (role),
  INDEX idx_users_verification_status (verification_status)
);

CREATE TABLE IF NOT EXISTS properties (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  landlord_id VARCHAR(64) NOT NULL,
  landlord_name VARCHAR(120) NULL,
  landlord_phone VARCHAR(30) NULL,
  landlord_whatsapp VARCHAR(30) NULL,
  landlord_bkash VARCHAR(50) NULL,
  landlord_nagad VARCHAR(50) NULL,
  title VARCHAR(255) NOT NULL,
  area VARCHAR(190) NULL,
  nearby_university VARCHAR(190) NULL,
  address TEXT NULL,
  map_latitude DECIMAL(10,7) NULL,
  map_longitude DECIMAL(10,7) NULL,
  map_label VARCHAR(255) NULL,
  map_link TEXT NULL,
  total_seats INT NOT NULL DEFAULT 1,
  available_seats INT NOT NULL DEFAULT 1,
  gender_preference VARCHAR(30) NOT NULL DEFAULT 'Any',
  room_type VARCHAR(40) NOT NULL DEFAULT 'Non Furnished',
  monthly_rent_per_seat DECIMAL(12,2) NOT NULL DEFAULT 0,
  security_deposit DECIMAL(12,2) NOT NULL DEFAULT 0,
  meal_system VARCHAR(40) NOT NULL DEFAULT 'Not Included',
  amenities_json JSON NULL,
  gate_closing_time VARCHAR(40) NULL,
  guest_policy TEXT NULL,
  smoking_rules TEXT NULL,
  attached_bath TINYINT(1) NOT NULL DEFAULT 0,
  filtered_water TINYINT(1) NOT NULL DEFAULT 0,
  lift TINYINT(1) NOT NULL DEFAULT 0,
  wifi TINYINT(1) NOT NULL DEFAULT 0,
  photos_json JSON NULL,
  appliances_json JSON NULL,
  description TEXT NULL,
  university_proximity VARCHAR(255) NULL,
  commute_minutes INT NULL,
  rental_month VARCHAR(7) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  publication_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  views INT NOT NULL DEFAULT 0,
  space_type VARCHAR(40) NULL,
  pets_allowed TINYINT(1) NOT NULL DEFAULT 0,
  bachelors_allowed VARCHAR(40) NULL,
  furnishing_type VARCHAR(40) NULL,
  bhk INT NULL,
  floor VARCHAR(40) NULL,
  nearest_landmark VARCHAR(190) NULL,
  washroom_type VARCHAR(60) NULL,
  cooling_facility VARCHAR(60) NULL,
  car_parking TINYINT(1) NOT NULL DEFAULT 0,
  square_feet_area INT NOT NULL DEFAULT 0,
  about_property TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_properties_landlord (landlord_id),
  INDEX idx_properties_publication (publication_status),
  INDEX idx_properties_active (is_active),
  CONSTRAINT fk_properties_landlord FOREIGN KEY (landlord_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS property_applications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  property_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  tenant_name VARCHAR(120) NULL,
  tenant_email VARCHAR(190) NULL,
  tenant_phone VARCHAR(30) NULL,
  student_id_type VARCHAR(30) NOT NULL DEFAULT 'Student ID',
  seats_requested INT NOT NULL DEFAULT 1,
  document_url TEXT NULL,
  roommate_request TINYINT(1) NOT NULL DEFAULT 0,
  note TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  verification_score DECIMAL(10,2) NULL,
  verification_confidence DECIMAL(10,2) NULL,
  verification_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  verification_flags JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_applications_property (property_id),
  INDEX idx_applications_tenant (tenant_id),
  CONSTRAINT fk_applications_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT fk_applications_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rent_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  property_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  month VARCHAR(7) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  provider VARCHAR(60) NULL,
  transaction_id VARCHAR(120) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  source VARCHAR(30) NOT NULL DEFAULT 'Manual',
  paid_at DATETIME NULL,
  ssl_session_key VARCHAR(120) NULL,
  ssl_preferred_method VARCHAR(60) NULL,
  ssl_validation_id VARCHAR(120) NULL,
  ssl_bank_transaction_id VARCHAR(120) NULL,
  ssl_card_type VARCHAR(60) NULL,
  ssl_card_issuer VARCHAR(120) NULL,
  ssl_card_brand VARCHAR(60) NULL,
  ssl_card_subtype VARCHAR(60) NULL,
  ssl_validated_amount DECIMAL(12,2) NULL,
  ssl_currency VARCHAR(20) NULL,
  ssl_gateway_status VARCHAR(30) NULL,
  slip_id VARCHAR(120) NULL,
  slip_generated_at DATETIME NULL,
  slip_download_url TEXT NULL,
  slip_note TEXT NULL,
  assistant_status VARCHAR(30) NULL,
  assistant_flags JSON NULL,
  assistant_expected_amount DECIMAL(12,2) NULL,
  assistant_paid_amount DECIMAL(12,2) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_payments_property (property_id),
  INDEX idx_payments_tenant (tenant_id),
  INDEX idx_payments_month (month),
  CONSTRAINT fk_payments_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS property_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  property_id VARCHAR(64) NOT NULL,
  sender_id VARCHAR(64) NOT NULL,
  sender_name VARCHAR(120) NULL,
  sender_role VARCHAR(30) NULL,
  message TEXT NOT NULL,
  moderation_score DECIMAL(10,2) NULL,
  moderation_risk_level VARCHAR(30) NULL,
  moderation_flags JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_messages_property (property_id),
  CONSTRAINT fk_messages_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS property_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  property_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  tenant_name VARCHAR(120) NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 5.0,
  comment TEXT NULL,
  moderation_score DECIMAL(10,2) NULL,
  moderation_risk_level VARCHAR(30) NULL,
  moderation_flags JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reviews_property (property_id),
  CONSTRAINT fk_reviews_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(30) NULL,
  topic VARCHAR(120) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Open',
  admin_notes TEXT NULL,
  resolved_at DATETIME NULL,
  resolved_by VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_contact_status (status)
);

CREATE TABLE IF NOT EXISTS blogs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  content LONGTEXT NOT NULL,
  cover_image_url TEXT NULL,
  author_id VARCHAR(64) NULL,
  likes_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_blogs_author (author_id),
  CONSTRAINT fk_blogs_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS intelligence_thresholds (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fraud_threshold INT NOT NULL DEFAULT 70,
  quality_threshold INT NOT NULL DEFAULT 60,
  price_delta_threshold INT NOT NULL DEFAULT 15,
  risk_threshold INT NOT NULL DEFAULT 60,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO intelligence_thresholds (fraud_threshold, quality_threshold, price_delta_threshold, risk_threshold)
SELECT 70, 60, 15, 60
WHERE NOT EXISTS (SELECT 1 FROM intelligence_thresholds LIMIT 1);